services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    env_file:
      - 'localstack/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./localstack/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
      - ./localstack/forms:/etc/localstack/forms:ro
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - grants-ui-config-api-net

  mongodb:
    image: mongo:7.0
    networks:
      - grants-ui-config-api-net
    ports:
      - "${MONGO_PORT:-27017}:27017"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval 'db.runCommand({ping:1}).ok' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    command:
      ["mongod", "--replSet", "mongoRepl", "--bind_ip", "localhost,mongodb"]
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    restart: always

  mongo-ready:
    image: mongo:7.0
    networks: [grants-ui-config-api-net]
    environment:
      PRIMARY: "mongodb:27017"
      REPLSET: "mongoRepl"
    volumes:
      - ./scripts/wait-for-replicaset.sh:/wait-for-replicaset.sh:ro
    entrypoint: ["/bin/bash", "/wait-for-replicaset.sh"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh 'mongodb://mongodb:27017/?directConnection=true' --quiet --eval 'db.hello().isWritablePrimary' | grep -q true || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 60

  grants-ui-config-api:
    build:
      context: .
      target: development
    ports:
      - '3011:3011'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'localstack/aws.env'
    environment:
      PORT: 3011
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      JWT_SECRET: ${JWT_SECRET:-config-api-jwt-secret}
      CONFIG_BROKER_URL: '${CONFIG_BROKER_URL:-http://grants-config-broker:3012}'
      CONFIG_BROKER_AUTH_TOKEN: '${CONFIG_BROKER_AUTH_TOKEN:-config-broker-auth-token}'
      CONFIG_BROKER_ENCRYPTION_KEY: '${CONFIG_BROKER_ENCRYPTION_KEY:-config-broker-encryption-key}'
      FORMS_API_SLUGS: ${FORMS_API_SLUGS:-example-grant-with-auth}
      DEFAULT_FORM_ORGANISATION: ${DEFAULT_FORM_ORGANISATION:-Defra}
      DEFAULT_FORM_TEAM_NAME: ${DEFAULT_FORM_TEAM_NAME:-Digital Delivery}
      DEFAULT_FORM_TEAM_EMAIL: '${DEFAULT_FORM_TEAM_EMAIL:-digitaldelivery@defra.gov.uk}'
      DEFAULT_FORM_NOTIFICATION_EMAIL: '${DEFAULT_FORM_NOTIFICATION_EMAIL:-digitaldelivery@defra.gov.uk}'
    networks:
      - grants-ui-config-api-net
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  grants-config-broker:
    image: defradigital/grants-config-broker:latest
    pull_policy: always
    ports:
      - '3012:3012'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'localstack/aws.env'
    environment:
      PORT: 3012
      NODE_ENV: development
      AWS_ENDPOINT_URL: http://localstack:4566
      CONFIG_BUCKET_NAME: configs-bucket
      MONGO_URI: mongodb://mongodb:27017/
      GRANTS_CONFIG_BROKER_AUTH_TOKEN: '${GRANTS_CONFIG_BROKER_AUTH_TOKEN:-config-broker-auth-token}'
      GRANTS_CONFIG_BROKER_ENCRYPTION_KEY: '${GRANTS_CONFIG_BROKER_ENCRYPTION_KEY:-config-broker-encryption-key}'
      SERVICE_VERSION: 1.0.0
    networks:
      - grants-ui-config-api-net
    volumes:
      - ./localstack/config-broker:/home/node/config

volumes:
  mongodb-data:
  mongodb-config:

networks:
  grants-ui-config-api-net:
    driver: bridge
    name: grants-ui-config-api-net
